### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by JoseAngelB** [jieran233/PrimoCacheBuster#1]
Having windows 11 and python 3.11.1:
```
File "D:\primocachebuster.py", line 55, in kill_process
    if o['errinfo'] == '':
       ~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jieran233** [comment]
Hi,

Thank you for taking the time to report this issue. However, I must inform you that I do not plan to maintain this project in the future. This is just a toy project I created for fun and to learn new things, and I don't have the resources or the expertise to continue working on it.

I apologize for any inconvenience this may cause you, and I appreciate your interest in the project. Please feel free to fork the repository and continue working on it yourself, or to submit a pull request if you think you can fix the issue.

Thank you for your understanding.

(Written by ChatGPT)
